Source/config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :items
  resources :trips
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  resources :comments
    resources :permissions do
    member do
      get 'accept'
      get 'refuse'
    end
  end

  root 'users#index'

end

Source/app/models/trip.rb
class Trip < ActiveRecord::Base
  has_many :comments
  has_many :items
  has_many :stops
  has_many :permissions
  has_many :users, through: :permissions
  belongs_to :transport
end

Source/app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]
  # Allows disconnected users to access the index and show pages only.
  before_filter :authenticate_user!, except: [:index, :show]
  # The user must be admin of the trip in order to edit or delete it.
  before_filter :check_if_admin_of_trip, only: [:edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    # Get permissions in order to show/hide "Edit"/"Destroy" links on each
    # trip.
    if user_signed_in?
        @permissions = Permission.where(user_id: current_user.id)
        @admin_permission = Permission_type.find_by(permission: "admin").id
    end

    # Get public trips and the private trip the connected user has an access on.
    if user_signed_in?
        # Show all trips if the user is super-admin
        if current_user.super_admin
            @trips = Trip.all
        else
            sqlRequest = "
                SELECT *
                FROM trips AS t
                WHERE public = 1
                    OR id IN (SELECT p.trip_id FROM permissions AS p WHERE p.user_id = ? AND accepted = 1)"
            @trips = Trip.find_by_sql [sqlRequest, current_user.id]
        end
    else
        @trips = Trip.where(public: 1)
    end
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @comments = @trip.comments
    @comment = Comment.new

    @items = @trip.items
    @item = Item.new

    # Get participants of the trip.
    users_ids = Permission.select(:user_id).where(trip_id: @trip.id)
    @users = User.where(:id => users_ids)

    # Get permissions of the trip in order to show admins.
    @permissions = Permission.where(trip_id: @trip.id)
    @admin_permission = Permission_type.find_by(permission: "admin").id

    @transport = Transport.find(@trip.transport_id).name
  end

  # GET /trips/new
  def new
    @trip = Trip.new

    @items = @trip.items
    @item = Item.new
    @transports = Transport.all
    @users = User.where.not(id: current_user.id)
  end

  # GET /trips/1/edit
  def edit

    @items = @trip.items
    @item = Item.new

    @transports = Transport.all

    # Get participants of the trip.
    users_ids = Permission.select(:user_id).where(trip_id: @trip.id)
    @participants = User.where(:id => users_ids)
    # Get users who don't belong to the trip.
    @users = User.where.not(:id => users_ids)

    # Get permissions of the trip in order to show admins.
    @permissions = Permission.where(trip_id: @trip.id)
    @admin_permission = Permission_type.find_by(permission: "admin").id
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        # Get the permission's type which represent an usual user and an admin one.
        permUser = Permission_type.find_by(permission: "user").id
        permAdmin = Permission_type.find_by(permission: "admin").id

        # Create current user's admin permission on the new created trip.
        adminPerm = Permission.new(:user_id => current_user.id, :trip_id => @trip.id, :permission_type_id => permAdmin, :accepted => 1)
        adminPerm.save
        # Create a "user" permission for each selected users.
        if params["users"]
            params["users"].each do |user|
                userId = user[2, user.length]

                # We don't add the current user, which is an admin.
                if userId != String(current_user.id)
                    currentPermission = user[0] == "1" ? permAdmin : permUser

                    perm = Permission.new(:user_id => userId, :trip_id => @trip.id, :permission_type_id => currentPermission, :accepted => 0)
                    perm.save
                end
            end
        end

        # Create each waypoint of the trip.
        if params['waypoints']
            i = 0
            params['waypoints'].each do |waypoint|
                i += 1
                w = Stop.new(:title => @trip.title + " - #{i}", :loc_lat => waypoint[1][0], :loc_lon => waypoint[1][1], :trip_id => @trip.id, :etape_nb => i)
                w.save
            end

            # If the endpoint is also the startpoint, add an extra stop.
            if params['arrivalEqualsStart']
                w = Stop.new(:title => @trip.title + " - #{i + 1}", :loc_lat => params["waypoints"]["0"][0], :loc_lon => params["waypoints"]["0"][1], :trip_id => @trip.id, :etape_nb => (i + 1))
                w.save
            end
        end

        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
     #abort(params["users"].inspect)

     respond_to do |format|
      if @trip.update(trip_params)
        # Get the permission's type which represent an usual user and an admin one.
        permUser = Permission_type.find_by(permission: "user").id
        permAdmin = Permission_type.find_by(permission: "admin").id

        # Remove each current permission.
        Permission.where(trip_id: @trip.id).each do |p|
            p.destroy
        end
        # Create current user's admin permission on the new created trip.
        adminPerm = Permission.new(:user_id => current_user.id, :trip_id => @trip.id, :permission_type_id => permAdmin, :accepted => 1)
        adminPerm.save
        # Create a "user" permission for each selected users.
        if params["users"]
            params["users"].each do |user|
                userId = user[2, user.length]

                # We don't add the current user, which is an admin.
                if userId != String(current_user.id)
                    currentPermission = user[0] == "1" ? permAdmin : permUser

                    perm = Permission.new(:user_id => userId, :trip_id => @trip.id, :permission_type_id => currentPermission, :accepted => 0)
                    perm.save
                end
            end
        end

        # Remove each current waypoint.
        Stop.where(trip_id: @trip.id).each do |s|
            s.destroy
        end
        # Create each waypoint of the trip.
        if params['waypoints']
            i = 0
            params['waypoints'].each do |waypoint|
                i += 1
                w = Stop.new(:title => @trip.title + " - #{i}", :loc_lat => waypoint[1][0], :loc_lon => waypoint[1][1], :trip_id => @trip.id, :etape_nb => i)
                w.save
            end

            # If the endpoint is also the startpoint, add an extra stop.
            if params['arrivalEqualsStart']
                w = Stop.new(:title => @trip.title + " - #{i + 1}", :loc_lat => params["waypoints"]["0"][0], :loc_lon => params["waypoints"]["0"][1], :trip_id => @trip.id, :etape_nb => (i + 1))
                w.save
            end
        end

        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    # First delete trip's permissions.
    @trip.permissions.each do |perm|
        perm.destroy
    end

    # Then delete the trip itself.
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:title, :description, :public, :start_date, :end_date, :transport_id)
    end

    # Check if the user if admin of the current trip, otherwise redirect it to
    # the trips list.
    def check_if_admin_of_trip
        trip_permission = Permission.where(user_id: current_user.id, trip_id: @trip.id).first
        admin_permission = Permission_type.find_by(permission: "admin").id

        redirect_to trips_url, notice: 'You are not admin of this trip!' unless (current_user.super_admin || trip_permission && trip_permission.permission_type_id == admin_permission)
    end
end

Source/app/helpers/trips_helper.rb
module TripsHelper
end

Source/app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Add each existing waypoints as hidden fields if the user is editing a trip. -->
  <% if !@trip.new_record? %>
    <% i = 1 %>
    <% @trip.stops.each do |s| %>
        <%= hidden_field_tag "waypoints[#{i - 1}][]", s.loc_lat, :id => "waypoint-#{i}-1" %>
        <%= hidden_field_tag "waypoints[#{i - 1}][]", s.loc_lon, :id => "waypoint-#{i}-2" %>
        <% i += 1 %>
    <% end %>
  <% end %>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" id="tripTabs" role="tablist">
    <li role="presentation" class="active"><a href="#summary" aria-controls="summary" role="tab" data-toggle="tab">Summary</a></li>
    <li role="presentation"><a href="#route" aria-controls="route" role="tab" data-toggle="tab" id="route-tab">Route</a></li>
    <li role="presentation"><a href="#participants" aria-controls="participants" role="tab" data-toggle="tab">Participants</a></li>
    <li role="presentation"><a href="#costs" aria-controls="costs" role="tab" data-toggle="tab" id="costs-tab">Costs</a></li>
  </ul>

  <!-- Tab panes -->
    <div class="tab-content tabAddEdit">
        <div role="tabpanel" class="tab-pane fade in active" id="summary">
            <div class="field">
              <%= f.label :title %><br>
              <%= f.text_field :title, class: "form-control" %>
            </div>
            <div class="field">
              <%= f.label :description %><br>
              <%= f.text_area :description, class: "form-control" %>
            </div>
            <div class="field">
              <%= f.check_box :public %>
              <%= f.label :public %>
            </div>
            <div class="field">
              <%= f.label :start_date %><br>
              <%= f.datetime_select :start_date %>
            </div>
            <div class="field">
              <%= f.label :end_date %><br>
              <%= f.datetime_select :end_date %>
            </div>
        </div>

        <div role="tabpanel" class="tab-pane fade" id="route">
            <div class="field">
              <%= f.label "Transport: " %>
              <%= f.collection_select :transport_id, @transports, :id, :name %>
            </div>
            <div class="tripStops">
                <div class="stops">
                    <h4><strong>Stops</strong></h4>
                    <div id="stops-instructions">First select the start of your trip by clicking on the map to the right.</div>
                    <div class="stopsOptions" id="stopsOptions">
                        <input type="button" class="btn btn-primary removeLastStop" onclick="removeLastStop()" value="Remove last stop" /><br/>
                        <input class="arrivalEqualsStart" id="arrivalEqualsStart" name="arrivalEqualsStart" title="Check me if you want your trip to be a loop." type="checkbox" value="yes">
                        <span data-placement="bottom" data-toggle="tooltip" data-trigger="manual" id="arrivalEqualsStartText" title="Check me if you want your trip to be a loop.">The arrival stop is also the start one (count as an extra point!)</span>
                    </div>

                    <div class="distanceDurationDivs" id="distance"></div>
                    <div class="distanceDurationDivs" id="duration"></div>

                    <input type="button" class="btn btn-primary calculateRoute" id="calculateRoute" onclick="calcRoute()" value="Calculate route..." /><br/>
                </div>
                <div class="map" id="map"></div>
            </div>
        </div>

        <div role="tabpanel" class="tab-pane fade" id="participants">
            <div class="field">
              <table width="100%">
                  <tr>
                      <td><%= f.label "Users" %></td>
                      <td></td>
                      <td><%= f.label "Participants" %></td>
                  </tr>
                  <tr>
                      <td class="userSelectsTd">
                          <select class="userSelects" id="usersSelect" multiple="multiple">
                              <%= if @users
                                  @users.each do |user| %>
                                    <option admin="0" value="0-<%= user.id %>" userId="<%= user.id %>"><%= user.user_name + " (" + user.first_name + " " + user.family_name + ")" %></option>
                                  <% end
                              end %>
                          </select>
                      </td>
                      <td class="userButtonTd">
                          <input class="addRemoveParticipantBtn" type="button" onclick="addParticipants()" value=">" /><br/>
                          <input class="addRemoveParticipantBtn" type="button" onclick="removeParticipants(<%= current_user.id %>)" value="<" /><br/>
                          <input type="button" onclick="toggleAdmin(<%= current_user.id %>)" value="Toggle Admin" />
                      </td>
                      <td class="userSelectsTd">
                          <select class="userSelects" id="participantsSelect" name="users[]" multiple="multiple">
                              <% if @participants
                                  @participants.each do |participant|
                                      isAdmin = 0

                                      @permissions.each do |p|
                                          if p.user_id == participant.id
                                              if p.permission_type_id == @admin_permission
                                                  isAdmin = 1
                                              end

                                              break
                                          end
                                      end
                              %>

                                <option admin="<%= isAdmin %>"<%= isAdmin == 1 ? " class=adminUser" : "" %><%= participant.id == current_user.id ? " iscurrent=1" : "" %> id="participant-<%= participant.id %>" value="<%= isAdmin.inspect + "-" + participant.id.inspect %>" userId="<%= participant.id %>"><%= participant.user_name + " (" + participant.first_name + " " + participant.family_name + ")" %></option>

                              <% end
                          end %>
                          </select>
                      </td>
                  </tr>
              </table>
            </div>
        </div>

        <div role="tabpanel" class="tab-pane fade" id="costs">
            <div class="calculateRouteWarning" id="calculateRouteWarning">Please first calculate the trip's route by clicking the "Route" tab, then come back here.</div>
            Please enter the medium cost per kilometer:
            <input disabled="disabled" id="costPerKm" min="0" name="costPerKm" onchange="calculateCosts()" placeholder="0.00" step="0.05" type="number"> CHF
            <input class="calculateCostsButton" disabled="disabled" id="calculateCostsBtn" onclick="calculateCosts()" type="button" value="Calculate costs!" /><br/>
            <div class="tripCosts"><u>Costs:</u><br/><div class="costs" id="tripCosts">-</div></div>
        </div>
    </div>

  <br/>

  <div class="actions">
    <%= f.submit(class: "btn btn-primary", onclick: "selectAllParticipants()") %>
  </div>
<% end %>

Source/app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

Source/app/views/trips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trips</h1>

<table class="tripTable">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Transport</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.public ? image_tag("public.png", size: "25", "data-toggle": "tooltip", "data-placement": "left", title: "This is a public trip.") : "" %></td>
        <td><%= link_to trip.title, trip %></td>
        <td><%= trip.start_date.strftime("%d.%m.%y %H:%M") %></td>
        <td><%= trip.end_date.strftime("%d.%m.%y %H:%M") %></td>
        <td><%= trip.transport.name %></td>
        <td>
            <%
                # Super-admin can edit/remove all trips.
                if current_user && current_user.super_admin %>
                    <%= link_to image_tag("edit.png", size: "25"), edit_trip_path(trip) %>
                    <%= link_to image_tag("delete.png", size: "25", class: "deleteIcon"), trip, method: :delete, data: { confirm: 'Are you sure?' } %>
                <% else
                    # Show the "Edit" and "Destroy" links if the user is admin.
                    if @permissions
                        @permissions.each do |p|
                            if p.trip_id == trip.id
                                if p.permission_type_id == @admin_permission %>
                                    <%= link_to image_tag("edit.png", size: "25"), edit_trip_path(trip) %>
                                    <%= link_to image_tag("delete.png", size: "25", class: "deleteIcon"), trip, method: :delete, data: { confirm: 'Are you sure?' } %>
                                <% end

                                break
                            end
                        end
                    end
            end
            %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trip', new_trip_path %><br/>
<%= link_to "Home", root_path %>

Source/app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

Source/app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<!-- Add each existing waypoints as hidden fields if the user is editing a trip. -->
<% i = 1 %>
<% @trip.stops.each do |s| %>
  <%= hidden_field_tag "waypoints[#{i - 1}][]", s.loc_lat, :id => "waypoint-#{i}-1" %>
  <%= hidden_field_tag "waypoints[#{i - 1}][]", s.loc_lon, :id => "waypoint-#{i}-2" %>
  <% i += 1 %>
<% end %>

<!-- Nav tabs -->
<ul class="nav nav-tabs" id="tripTabs" role="tablist">
  <li role="presentation" class="active"><a href="#summary" aria-controls="summary" role="tab" data-toggle="tab">Summary</a></li>
  <li role="presentation"><a href="#route" aria-controls="route" role="tab" data-toggle="tab" id="route-tab">Route</a></li>
  <li role="presentation"><a href="#participants" aria-controls="participants" role="tab" data-toggle="tab">Participants</a></li>
  <li role="presentation"><a href="#costs" aria-controls="costs" role="tab" data-toggle="tab" id="costs-tab">Costs</a></li>
  <li role="presentation"><a href="#packing" aria-controls="packing" role="tab" data-toggle="tab">Packing List</a></li>
  <% if user_signed_in? %>
    <li role="presentation"><a href="#comments" aria-controls="comments" role="tab" data-toggle="tab">Comments</a></li>
  <% end %>
</ul>

<!-- Tab panes -->
<div class="tab-content tabShow">
    <div role="tabpanel" class="tab-pane fade in active" id="summary">
        <p>
          <strong>Title:</strong>
          <%= @trip.title %>
        </p>

        <p>
          <strong>Description:</strong>
          <%= @trip.description %>
        </p>

        <p>
          <strong>Public:</strong>
          <%= @trip.public %>
        </p>

        <p>
          <strong>Start date:</strong>
          <%= @trip.start_date.strftime("%d-%m-%Y %H:%M:%S") %>
        </p>

        <p>
          <strong>End date:</strong>
          <%= @trip.end_date.strftime("%d-%m-%Y %H:%M:%S") %>
        </p>
    </div>

    <div role="tabpanel" class="tab-pane fade" id="route">
        <p>
          <strong>Transport:</strong>
          <span id="transport_name"><%= @transport %></span>
        </p>

        <div class="mapBase" id="mapTripDetails"></div>
    </div>

    <div role="tabpanel" class="tab-pane fade" id="participants">
        <p>
            <strong>Here are the crazy adventurers of the trip!</strong><br/>
            Administrators appear in bold.<br/>
        </p>
        <ul>
        <%
            @users.each do |u|
                isAdmin = 0

                @permissions.each do |p|
                    if p.user_id == u.id
                        if p.permission_type_id == @admin_permission
                            isAdmin = 1
                        end

                        break
                    end
                end
            %>
            <% if isAdmin == 1 %>
                    <li><strong><%= u.user_name + " (" + u.first_name + " " + u.family_name + ")" %></strong></li>
            <% else %>
                    <li><%= u.user_name + " (" + u.first_name + " " + u.family_name + ")" %></li>
            <% end
            end %>
        </ul>
    </div>

    <div role="tabpanel" class="tab-pane fade" id="costs">
        <div class="calculateRouteWarning" id="calculateRouteWarning">Please first calculate the trip's route by clicking the "Route" tab, then come back here.</div>
        Please enter the medium cost per kilometer:
        <input disabled="disabled" id="costPerKm" min="0" name="costPerKm" onchange="calculateCosts()" placeholder="0.00" step="0.05" type="number"> CHF
        <input class="calculateCostsButton" disabled="disabled" id="calculateCostsBtn" onclick="calculateCosts()" type="button" value="Calculate costs!" /><br/>
        <div class="tripCosts"><u>Costs:</u><br/><div class="costs" id="tripCosts">-</div></div>
    </div>

    <div role="tabpanel" class="tab-pane fade" id="packing">
        <p>
          <strong>Packing list:</strong>
        </p>

        <ul id="item_list">
          <% @items.each do |item| %>
            <li> 
                <%= item.name %>
                <%= link_to 'Edit', edit_item_path(item) %>
                <%= link_to 'Destroy', item, :confirm => 'Are you sure?', :method => :delete, :remote => true, :class => "item" %>  
            </li>
          <% end %>
        </ul>

        <% if user_signed_in? %>
        <p>
          <%= form_for(@item,:remote => true) do |f| %>
            <strong>Add an item:</strong> <%= f.text_field :name %> <br>
            <%= f.hidden_field :trip_id, :value => @trip.id %>
            <%= f.submit "Add" %>
          <% end %>
        </p>
        <% end %>
    </div>

    <div role="tabpanel" class="tab-pane fade" id="comments">
        <p>
          <strong>Comments:</strong>
        </p>

        <ul id="comment_list">
          <% @comments.each do |comment| %>
            <li> <%= comment.text %> | <%= comment.creation_date.strftime("%d-%m-%Y %H:%M:%S") %> | <%= comment.user.user_name %>
               <%= link_to 'Edit', edit_comment_path(comment) %>
               <%= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete, :remote => true, :class => "comment" %>
            </li>
          <% end %>
        </ul>
        <% if user_signed_in? %>
          <p>
            <%= form_for(@comment,:remote => true) do |f| %>
              <strong> Add a comments:</strong> <%= f.text_field :text %> <br>
              <%= f.hidden_field :user_id, :value => current_user.id %>
              <%= f.hidden_field :trip_id, :value => @trip.id %>
              <%= f.submit "Add" %>
            <% end %> 
          </p>
        <% end %>
    </div>
</div>

<br/>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>