Source/config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :items
  resources :trips
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  resources :comments
    resources :permissions do
    member do
      get 'accept'
      get 'refuse'
    end
  end

  root 'users#index'

end

Source/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :comments
  has_many :permissions
  has_many :trips, through: :permissions
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Source/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index]

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    @trips = Trip.where(public: 1)[0 .. 4]
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_name, :first_name, :family_name, :super_admin, :phone)
    end
end

Source/app/helpers/users_helper.rb
module UsersHelper
end

Source/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :family_name %><br>
    <%= f.text_field :family_name %>
  </div>
  <div class="field">
    <%= f.label :super_admin %><br>
    <%= f.check_box :super_admin %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Source/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

Source/app/views/users/index.html.erb
<script>
    function slidePage() {
        $('html, body').animate({
            scrollTop: $("#mainContainer").offset().top
        }, 1000);
    }
</script>

<h1> Plan your trip ! </h1>

Adventure Trip is a website that allows you to plan your roadtrips with your friends and share them to the world. It facilitates interactions between adventurers and can bring inspiration to the undecided folks who have no idea where to go during their trip.

<hr class="containerFluidTopSeparation">

<div class="container-fluid">
  <div class="row">
    <div class="col-md-4 columns">
      <h4><%= image_tag("pin-on-map.png", size: "25", class: "homeIcons") %>Plan</h4>
      Plan your trip by easily picking stops you want to make. Choose a transport mode and automatically get an estimation of time. Add a packing-list so you won't forget anything to bring.
    </div>
    <div class= "col-md-4 columns">
      <h4><%= image_tag("men-shaking-hands.png", size: "25", class: "homeIcons") %>Invite your friends</h4>
      Ask your friends to join your trip. They can leave a message and contribute to the planning by also adding objects to the packing-list.
    </div>
    <div class= "col-md-4 columns">
      <h4><%= image_tag("public.png", size: "25", class: "homeIcons") %>Share it to the world</h4>
      Set your trip in public mode and show it to anybody. Inspire future adventurers to go on a trip like you did.
    </div>
  </div>
</div>

<hr class="containerFluidBottomSeparation">

<h4> Last public trips :</h4>

<table class="tripTable">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Transport</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= image_tag("public.png", size: "25", "data-toggle": "tooltip", "data-placement": "left", title: "This is a public trip.") %></td>
        <td><%= link_to trip.title, trip %></td>
        <td><%= trip.start_date.strftime("%d.%m.%y %H:%M") %></td>
        <td><%= trip.end_date.strftime("%d.%m.%y %H:%M") %></td>
        <td><%= trip.transport.name %></td>
        <td>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>

<%= link_to "Take a look at all existing trips...", trips_path %>

<% if user_signed_in? %>
    <br/><%= link_to "Create a new trip!", new_trip_path %>
<% end %>

Source/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

Source/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @user.user_name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Family name:</strong>
  <%= @user.family_name %>
</p>

<p>
  <strong>Super admin:</strong>
  <%= @user.super_admin %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>